"""empty message

Revision ID: 57971d8bcfcb
Revises: 2b32c8dd34d4
Create Date: 2016-07-08 02:03:05.154007

"""

# revision identifiers, used by Alembic.
revision = '57971d8bcfcb'
down_revision = '2b32c8dd34d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blag', sa.Column('tagss', sa.String(), nullable=True))
    op.drop_column('blag', 'tags')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blag', sa.Column('tags', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('blag', 'tagss')
    ### end Alembic commands ###
