"""empty message

Revision ID: 93b8e3b8a040
Revises: 57971d8bcfcb
Create Date: 2016-07-08 02:03:19.164948

"""

# revision identifiers, used by Alembic.
revision = '93b8e3b8a040'
down_revision = '57971d8bcfcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blag', sa.Column('tags', sa.String(), nullable=True))
    op.drop_column('blag', 'tagss')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blag', sa.Column('tagss', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blag', 'tags')
    ### end Alembic commands ###
